version: "3.6"
services:
    headerapp:
        image: mepples21/headerapp:latest
        container_name: headerapp
        restart: always
        ports: 
          - "3000:8085"
    samlapp:
        image: 
        container_name: 
        restart: always
        ports: 
          - 
    oidcapp:
        image: 
        container_name: 
        restart: always
        ports: 
          - 
    kerberosapp:
        image: 
        container_name: 
        restart: always
        ports: 
          - 
networks:
    default:
        driver: bridge