version: "3.6"
services:
    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock --admin-password '$$2y$$10$$pzoGsHsnjXAi2UnPOxpY8uDd8J6Ob9koNqVRrZHK6ZKLmVjnVm3ri'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${USERDIR}/docker/portainer/data:/data
          - ${USERDIR}/docker/shared:/shared
        environment:
          - TZ=${TZ}
        ports: 
          - "9000:9000"
        networks:
          - web
        labels:
          - "traefik.enable=true"
          - "traefik.backend=portainer"
          - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
#          - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
          - "traefik.port=9000"
          - "traefik.docker.network=web"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=example.com"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
    header-app:
        image: fhakamine/header-app-tester
        container_name: header-app
        restart: always
        ports: 
          - "3000:3000"
        networks: 
          - web
        labels: 
          - "traefik.enable=true"
          - "traefik.backend=portainer"
          - "traefik.frontend.rule=Host:headerapp.${DOMAINNAME}"
#          - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
          - "traefik.port=9000"
          - "traefik.docker.network=web"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=example.com"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
    saml-app:
        image: beryju/saml-test-sp
        container_name: saml-app
        restart: always
        environment: 
          - SP_BIND=0.0.0.0:9000
          - SP_ROOT_URL=http://localhost:9000
          - SP_ENTITY_ID=saml-test-sp
        networks: 
          - web
        labels:
          - "traefik.enable=true"
          - "traefik.backend=portainer"
          - "traefik.frontend.rule=Host:samlapp.${DOMAINNAME}"
#          - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
          - "traefik.port=9000"
          - "traefik.docker.network=web"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=example.com"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
    traefik:
        hostname: traefik
        image: traefik:v1.7.24
        container_name: traefik
        restart: always
        domainname: ${DOMAINNAME}
        networks:
          - default
          - web
        ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
        environment:
          - CLOUDFLARE_EMAIL=$${CLOUDFLARE_EMAIL}
          - CLOUDFLARE_API_KEY=$${CLOUDFLARE_API_KEY}
          #- "constraint:node.id==yanih3skeet4jkd56v8wv2rho"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=traefik"
          - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
#          - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"
          - "traefik.port=8080"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=example.com"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ${USERDIR}/docker/traefik:/etc/traefik
          - ${USERDIR}/docker/shared:/shared
networks:
    web:
        external:
            name: web
    default:
        driver: bridge